import './css/style.css';

import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

// import Header from "@/components/ui/header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body
        className={`${GeistSans.className} bg-slate-950 text-base text-slate-200 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {/* <Header /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
